### ISSUE TITLE
traceCaller throws TypeError: Cannot call method 'indexOf' of nulle

### ISSUE THREAD

**Issue by mwittig** [mwittig/winston-dconsole#2]
```
TypeError: Cannot call method 'indexOf' of null
    at traceCaller (C:\Users\marcus\Documents\Devel\ComX\cdk\lib\logging\node_modules\winston-dconsole\winston-dconsole.js:17:27)
    at Dconsole.log (C:\Users\marcus\Documents\Devel\ComX\cdk\lib\logging\node_modules\winston-dconsole\winston-dconsole.js:61:17)
    at transportLog (C:\Users\marcus\Documents\Devel\ComX\cdk\lib\logging\node_modules\winston\lib\winston\logger.js:228:15)
    at C:\Users\marcus\Documents\Devel\ComX\cdk\lib\logging\node_modules\winston\node_modules\async\lib\async.js:157:13
    at _each (C:\Users\marcus\Documents\Devel\ComX\cdk\lib\logging\node_modules\winston\node_modules\async\lib\async.js:57:9)
    at Object.async.each (C:\Users\marcus\Documents\Devel\ComX\cdk\lib\logging\node_modules\winston\node_modules\async\lib\async.js:156:9)
    at Logger.log (C:\Users\marcus\Documents\Devel\ComX\cdk\lib\logging\node_modules\winston\lib\winston\logger.js:240:9)
    at Client.<anonymous> (C:\Users\marcus\Documents\Devel\ComX\cdk-xmpp\src\XMPPSession.js:194:16)
    at Client.emit (events.js:95:17)
    at Client._handleStanza (C:\Users\marcus\Documents\Devel\ComX\cdk-xmpp\node_modules\node-xmpp-client\lib\Client.js:228:12)
```

**Comment by mwittig** [comment]
Released 0.0.5
